source 'https://rubygems.org'

gem 'rack', '~> 2.1.4'
gem 'roda', '~> 2.27.0'
gem 'celluloid', '~> 0.17.3'
gem 'tilt-jbuilder', '>= 0.7.0'
gem 'mutations', '>= 0.8.2'
gem 'mongoid', '~> 6.0.0'
gem 'symmetric-encryption', '~> 3.9.1'
gem 'activesupport', '~> 5.2', '>= 5.2.4.3'
gem 'faye-websocket', '~> 0.11.0'
gem 'websocket-driver', '~> 0.7.0'
gem 'kontena-websocket-client', '~> 0.1.1'
gem 'puma', '>= 4.3.12'
gem 'random_token'
gem 'msgpack'
gem 'httpclient', '~> 2.3'
gem 'authority', '>= 3.2.0'
gem 'mongoid-enum'
gem 'rollbar', require: false
gem 'rbtrace', '>= 0.4.9', require: false
gem 'acme-client', '>= 0.3.5'
gem 'json-jwt', '= 1.11.0'
gem 'jsonpath'
gem 'json-serializer'
gem 'bcrypt'
gem 'rack-attack', '>= 5.1.0'
gem 'lru_redux', '~> 1.1.0'
gem 'hkdf', '~> 0.3.0'

group :development, :test do
  gem 'dotenv'
  gem 'rspec', '~> 3.3.0', require: false
  gem 'mongoid-rspec', '~> 4.0.0', require: false
  gem 'rack-test', '>= 0.6.3', require: false
  gem 'rerun', '>= 0.11.0', require: false
  gem 'simplecov', require: false
  gem 'webmock', '>= 1.22.1', require: false
end
