source 'https://rubygems.org'

gem 'rack', '~> 2.2.8', '>= 2.2.8.1'
gem 'roda', '~> 2.27.0'
gem 'celluloid', '~> 0.17.3'
gem 'tilt-jbuilder', '>= 0.7.0'
gem 'mutations', '>= 0.8.2'
gem 'mongoid', '~> 7.0.12'
gem 'symmetric-encryption', '~> 3.9.1'
gem 'activesupport', '~> 6.1', '>= 6.1.7.3'
gem 'faye-websocket', '~> 0.10.7'
gem 'websocket-driver', '~> 0.6.2'
gem 'kontena-websocket-client', '~> 0.1.1'
gem 'puma', '>= 5.6.8'
gem 'random_token'
gem 'msgpack'
gem 'httpclient', '~> 2.3'
gem 'authority', '>= 3.2.0'
gem 'mongoid-enum'
gem 'rollbar', require: false
gem 'rbtrace', require: false
gem 'acme-client', '>= 0.4.0'
gem 'json-jwt', '= 1.6.0'
gem 'jsonpath'
gem 'json-serializer'
gem 'bcrypt'
gem 'rack-attack', '>= 5.1.0'
gem 'lru_redux', '~> 1.1.0'
gem 'hkdf', '~> 0.3.0'

group :development, :test do
  gem 'dotenv'
  gem 'rspec', '~> 3.3.0', require: false
  gem 'mongoid-rspec', '~> 4.0.0', require: false
  gem 'rack-test', '>= 0.6.3', require: false
  gem 'rerun', require: false
  gem 'simplecov', require: false
  gem 'webmock', require: false
end
